export const groupTypes = ['Caminhada', 'Carona'];

export const busStop = ['Parada EST',
						'Parada Pracinha da R. Altair Nunes',
						'Parada SEAS',
						'Parada Amazonas Shopping',
						'Parada Fametro',
						'Parada Manaus Plaza Shopping',
						'Parada China in Box',
						'Parada Alantic Tower Millenium Shopping'];

export const district = ['Adrianópolis',
						 'Aleixo',
						 'Alvorada',
						 'Armando Mendes',
						 'Betânia',
						 'Cachoeirinha',
						 'Centro',
						 'Chapada',
						 'Cidade de Deus',
						 'Cidade Nova',
						 'Colônia Antônio Aleixo',
						 'Colônia Oliveira Machado',
						 'Colônia Santo Antônio',
						 'Colônia Terra Nova',
						 'Compensa',
						 'Coroado',
						 'Crespo',
						 'Da Paz',
						 'Distrito Industrial I',
						 'Distrito Industrial II',
						 'Dom Pedro',
						 'Educandos',
						 'Flores',
						 'Gilberto Mestrinho',
						 'Glória',
						 'Japiim',
						 'Jorge Teixeira',
						 'Lago Azul',
						 'Lírio do Vale',
						 'Mauazinho',
						 'Monte das Oliveiras',
						 'Morro da Liberdade',
						 'Nossa Senhora Aparecida',
						 'Nossa Senhora das Graças',
						 'Nova Cidade',
						 'Nova Esperança',
						 'Novo Aleixo',
						 'Novo Israel',
						 'Parque 10 de Novembro',
						 'Petrópolis',
						 'Planalto',
						 'Ponta Negra',
						 'Praça 14 de Janeiro',
						 'Presidente Vargas',
						 'Puraquequara',
						 'Raiz',
						 'Redenção',
						 'Santa Etelvina',
						 'Santa Luzia',
						 'Santo Agostinho',
						 'Santo Antônio',
						 'São Francisco',
						 'São Geraldo',
						 'São Jorge',
						 'São José Operário',
						 'São Lázaro',
						 'São Raimundo',
						 'Tancredo Neves',
						 'Tarumã',
						 'Tarumã-Açu',
						 'Vila Buriti',
						 'Vila da Prata',
						 'Zumbi dos Palmares'];

export const hours = ['08', '09', '10', '11',
					  '12', '13', '14', '15',
					  '16', '17', '18', '19',
					  '20', '21', '22', '23'];

export const minutes = ['00', '05', '10', '15',
						'20', '25', '30', '35',
						'40', '45', '50', '55'];